nmap('<C-Left>' , ':BufferLineCyclePrev<CR>')
nmap('<C-Right>', ':BufferLineCycleNext<CR>')

nmap('<leader>p', ':GFiles<CR>')
nmap('<leader>g', ':Neogit<CR>')
nmap('<leader>t', ':NvimTreeToggle<CR>')
nmap('<leader>r', ':NvimTreeRefresh<CR>')
nmap('<leader>n', ':NvimTreeFindFile<CR>')
nmap('<leader>x', ':bp <BAR> bd #<CR>')
nmap('<leader>d', '<cmd>Gitsigns preview_hunk<CR>')
nmap('<leader>e', '<Cmd>exe v:count1 . "ToggleTerm"<CR>')
nmap('<leader>c', '<Plug>NERDCommenterToggle')
vmap('<leader>c', '<Plug>NERDCommenterToggle<CR>gv')

nmap('gd', '<Plug>(coc-definition)')
nmap('gy', '<Plug>(coc-type-definition)')
nmap('gc', '<Plug>(coc-declaration)')
nmap('gi', '<Plug>(coc-implementation)')
nmap('gr', '<Plug>(coc-references)')

nmap('<space>a', ':<C-u>CocList diagnostics<cr>')
nmap('<space>e', ':<C-u>CocList extensions<cr>')
nmap('<space>c', ':<C-u>CocList commands<cr>')
nmap('<space>o', ':<C-u>CocList outline<cr>')
nmap('<space>s', ':<C-u>CocList -I symbols<cr>')
nmap('<space>p', ':<C-u>CocListResume<cr>')

nmap('""', ':registers "0123456789abcdefghijklmnopqrstuvwxyz*+.<CR>')
nmap('K', ':call ShowDocumentation()<CR>')

imap('<TAB>', [[pumvisible() ? "\<C-n>" : CheckBackspace() ? "\<TAB>" : coc#refresh()]], true)
